#ifndef FLIGHTDYNAMICSCORE_GLOBAL_H
#define FLIGHTDYNAMICSCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLIGHTDYNAMICSCORE_LIBRARY)
#  define FLIGHTDYNAMICSCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FLIGHTDYNAMICSCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FLIGHTDYNAMICSCORE_GLOBAL_H
