#ifndef AVRDEVICESIMULATOR_GLOBAL_H
#define AVRDEVICESIMULATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AVRDEVICESIMULATOR_LIBRARY)
#  define AVRDEVICESIMULATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AVRDEVICESIMULATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AVRDEVICESIMULATOR_GLOBAL_H
