#ifndef SIMULATION_MISCELLANEOUS_GLOBAL_H
#define SIMULATION_MISCELLANEOUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATION_MISCELLANEOUS_LIBRARY)
#  define SIMULATION_MISCELLANEOUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATION_MISCELLANEOUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATION_MISCELLANEOUS_GLOBAL_H
